### ISSUE TITLE
Implement perimeter reveal as in MS minesweeper

### ISSUE THREAD

**Issue by wtho** [Knochenmark/minesweeper#112]
**Feature Request**
The perimeter reveal, as described in #63, was programmed after the description in the wikipedia minesweeper article (I guess the [german one](https://de.wikipedia.org/wiki/Minesweeper#Spielverlauf), as I could not find notes in the english one). The wiki actually describes the behavior as MS minesweeper acts, whereas the functionality from #88 does behave differently:
* MS only reveals the surrounding non-flag fields, if the double-clicked field's number has as many flags in its perimeter, so only if e. g. a `2`-field also has at least 2 flags in the 8 surrounding fields
* Knochenmark/minesweeper always reveals all surrounding non-flag fields

**Solution**
The perimeter reveal should only trigger, if sufficient flags are in the 8 surrounding fields, an additional check might be required.

**Additional context**
Try out here:
http://minesweeperonline.com/
Reveal a `1` field, right click and hold, and then also left-click to trigger the perimeter reveal, but it won't, as it has no flag. Then set a flag and try again.

**Comment by Knochenmark** [comment]
@wtho Pretty sure you are right with me using the German Wiki. Someone mentioned there was this perimeter check and to be fair I couldn't remember that there was something like this in the first place.

It shouldn't be too complicated to add this guard, since the Minefield interface has already a minecount property. Compare this with the count of flagged fields in the surrounding cells and you know if you can execute the perimeter check or not.
